### ISSUE TITLE
skip connection between blocks or layers?

### ISSUE THREAD

**Issue by gideonite** [xuyuwei/resnet-tf#1]
My understanding of the paper was that skip connections are between the beginning and end of residual blocks, i.e. after three layers. Is this correct? Or does it not matter?

It seems like you are putting skip connections between each each layer in each block.

**Comment by youwayx** [comment]
@gideonite i believe i am placing the skip connections between the beginning and end of residual blocks. however, i haven't looked at this code in a while so i could be wrong
